services:
   app1:
    build :
      context: ./
      dockerfile: Dockerfile.nodejs
    image: sample-port-app-nodejs
    container_name: app1
    environment :
     - NODENUMBER=1
    hostname: app1
    networks:
     - sample-app-used-port

   app2:
    image: sample-port-app-nodejs
    container_name: app2
    environment :
     - NODENUMBER=2
    hostname: app2
    networks:
     - sample-app-used-port

   auto-app:
    build :
      context: ./
      dockerfile: Dockerfile.nodejs
    image: sample-port-app-nodejs
    environment :
     - NODENUMBER=auto-node
    networks:
     - sample-app-used-port


   nginx:
    image: nginx:1.17
    container_name: loadbalancer
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
    networks:
      - sample-app-used-port

networks:
 sample-app-used-port:
  name : sample_app_used_port
  driver: bridge
  ipam:
   driver: default
   config: 
     - subnet: 172.18.213.0/24
